// This file is auto-generated by wrangler types
// Run `npm run types` to regenerate

interface Env {
  DB: D1Database;
  AI: Ai;
  ASSETS: Fetcher;
  ENVIRONMENT: string;
}

declare module 'astro:env' {
  export interface Runtime {
    env: Env;
  }
}
